//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "study")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub level: i32,
    pub index: i32,
    pub content: String,
    pub a: String,
    pub b: String,
    pub c: String,
    pub d: String,
    pub remark: String,
    pub result: i32,
    pub r#type: i32,
    pub create_date: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
